### ISSUE TITLE
Open source / license

### ISSUE THREAD

**Issue by cmnord** [HackGT/beehive#18]
Hi! I saw this project on http://hack.gt/code, but I don't see a license. What is the status on open-sourcing this project?

**Comment by illegalprime** [comment]
Hi @cmnord,
Thanks for your interest in this project!
Just fixed it in 6d9a812b3183385a79c9bc5fee5be1f201c15947, usually we use GPLv3.

As for its open source status, all the relevant code is already freely available to use.
I can offer some help in getting it set up, what are you thinking of using it for?

**Comment by cmnord** [comment]
Thanks! I'm a former HackMIT organizer, so I wanted to see if this is something the current team could look into for deployment.

**Comment by illegalprime** [comment]
Welcome! We've had a lot of success with it this past year, we use this system for code reviews and deployment and it lets us keep our apps standard.
