### ISSUE TITLE
Add logging and metrics.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/beehive#5]

**Comment by illegalprime** [comment]
@ehsanmasdar you might have already done this, maybe we need to codify it here?

**Comment by ehsanmasdar** [comment]
@illegalprime Is this to track metrics collection for all apps, or something specific to biodomes/deploy process? We should break this ticket into tickets to track this in each repo we want to add metrics to. I'll put all the documentation in hackgt/metrics

**Comment by illegalprime** [comment]
@ehsanmasdar this is to codify how to setup metrics, so we don't forget our artisan configs.

**Comment by ehsanmasdar** [comment]
@illegalprime See https://github.com/HackGT/metrics/blob/master/README.md
